-- COMPAÑÍA 1: 

INSERT INTO HU_CAT_MONEDA (NUM_CIA, CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ESTATUS) VALUES (1, 'MXN', 'Peso Mexicano', '$', 'A');
INSERT INTO HU_CAT_MONEDA (NUM_CIA, CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ESTATUS) VALUES (1, 'USD', 'Dolar Americano', 'US$', 'A');
INSERT INTO HU_CAT_MONEDA (NUM_CIA, CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ESTATUS) VALUES (1, 'EUR', 'Euro', '€', 'A');
INSERT INTO HU_CAT_MONEDA (NUM_CIA, CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ESTATUS) VALUES (1, 'GBP', 'Libra Esterlina', '£', 'A');

-- Empleados Cía 1
INSERT INTO HU_EMPLS (NUM_CIA, NUM_EMP, CLAVE_MONEDA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PUESTO) VALUES (1, 1001, 'MXN', 'David', 'Gomez', 'Perez', 'Dev Java Senior');
INSERT INTO HU_EMPLS (NUM_CIA, NUM_EMP, CLAVE_MONEDA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PUESTO) VALUES (1, 1002, 'USD', 'Laura', 'Sanchez', 'Diaz', 'Arquitecta');
INSERT INTO HU_EMPLS (NUM_CIA, NUM_EMP, CLAVE_MONEDA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PUESTO) VALUES (1, 1003, 'EUR', 'Sofia', 'Rossi', 'B', 'Gerente');

-- COMPAÑÍA 2
INSERT INTO HU_CAT_MONEDA (NUM_CIA, CLAVE_MONEDA, DESCRIPCION, SIMBOLO, ESTATUS) VALUES (2, 'USD', 'US Dollar', '$', 'A');

-- Empleados Cía 2
INSERT INTO HU_EMPLS (NUM_CIA, NUM_EMP, CLAVE_MONEDA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PUESTO) VALUES (2, 1001, 'USD', 'John', 'Doe', 'Smith', 'CEO North America');
INSERT INTO HU_EMPLS (NUM_CIA, NUM_EMP, CLAVE_MONEDA, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, PUESTO) VALUES (2, 5555, 'USD', 'Michael', 'Jordan', 'B', 'Sales VP');